version: '3.8'
services:
  app:
    container_name: trainTrackBackend
    env_file:
      - .env
    environment:
      DB_HOST: db
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - logs_volume:/usr/src/app/logs

  db:
    container_name: trainTrackDB
    image: mysql:8.0
    env_file:
      - .env
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
  logs_volume:
    driver: local
