version: '3.8'
services:
  app:
    container_name: trainTrackBackend
    image: exvaldev/traintrackbackend:latest
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: production
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_DRIVER: ${DB_DRIVER}
      PORT: ${PORT}
      URL: ${URL}
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - logs_volume:/usr/src/app/logs

  db:
    container_name: trainTrackDB
    image: mysql:8.0
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
  logs_volume:
    driver: local
